closes #14: set WEBPORTAL_PROVISIONINGTASKS_NUMBER_OF_VISIBLE_STATUS_LINES_MINUS_ONE to "3" instead of 3
I am trying to resolve an erro shown by travisCI with following content:
```
$ bundle exec rake db:migrate RAILS_ENV=test
rake aborted!
TypeError: no implicit conversion of Fixnum into String
/home/travis/build/oveits/ProvisioningEngine/config/application.rb:84:in `[]='
```